name: Post welcome comment
on: push
permissions:
  pull-requests: write
jobs:
  test:
    name: CHECKOUT TEST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        env:
          SHA: ${{ github.sha }}
          
          # echo "Hello2 ${{github.ref#refs/heads/}}"
          # echo "Hello3 $(${github.ref#refs/heads/})"
      - id: get_step
        run: |
          echo "HELLO"
          git fetch --depth=1 origin ${{ github.ref }}
          latest_commit=$(git rev-parse FETCH_HEAD)
          echo "latest $latest_commit"
          echo "Branch ${GITHUB_REF#refs/heads/}"
          echo "latest_commit=$(git rev-parse origin/${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
          echo "current_commit=$GITHUB_SHA" >> $GITHUB_OUTPUT
          echo "latest_commit=$(git rev-parse origin/${GITHUB_REF#refs/heads/})"
          echo "current_commit=${{ github.sha }}"
          echo $SHA
          echo "current_commit=$SHA"
          echo $GITHUB_SHA
          echo $GITHUB_REF
          echo "current_commit=$($SHA))"
    outputs:
      latest_commit: ${{ steps.get_step.outputs.latest_commit }}
      current_commit: ${{ steps.get_step.outputs.current_commit }}
  test_other:
    name: TEST WITHOUT CHECKOUT
    needs: test
    runs-on: ubuntu-latest
    env:
      LATEST_COMMIT: ${{ needs.test.outputs.latest_commit }}
    steps:
      - run: |
          echo "Welcome to the repository ${{ needs.test.outputs.latest_commit }}!"
          echo "$LATEST_COMMIT ! $GITHUB_SHA !"
          echo $GITHUB_SHA
          echo $GITHUB_REF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
