name: Post welcome comment
on:
  pull_request:
    types: [opened]
permissions:
  pull-requests: write
jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        env:
          SHA: ${{ github.sha }}
      - id: get_step
        run: |
          echo "latest_commit=$(git rev-parse $GITHUB_REF)" >> $GITHUB_OUTPUT
          echo "current_commit=$(git github.sha)" >> $GITHUB_OUTPUT
          echo "latest_commit=$(git rev-parse github.ref)"
          echo "current_commit=$(echo $SHA)"
          echo $SHA
          echo "current_commit=$SHA"
          echo $GITHUB_SHA
          echo $GITHUB_REF
          echo "current_commit=$($SHA))"
    outputs:
      latest_commit: ${{ steps.get_step.outputs.latest_commit }}
      current_commit: ${{ steps.get_step.outputs.current_commit }}
  build:
    name: Post welcome comment
    needs: get_current_step
    runs-on: ubuntu-latest
    env:
      CURRENT_COMMIT: ${{ needs.get_current_step.outputs.current_commit }}
    steps:
      - run: |
          gh pr comment $PR_URL --body "Welcome to the repository $(echo needs.get_current_step.outputs.latest_commit)!"
          gh pr comment $PR_URL --body "$CURRENT_COMMIT $(echo $CURRENT_COMMIT)!"
          echo $CURRENT_COMMIT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
